const form = document.getElementById("form")
const form = document.getElementById("name")
const form = document.getElementById("email")
const form = document.getElementById("password")
const form = document.getElementById("form")