const form = document.getElementById("form")
const name = document.getElementById("name")
const email = document.getElementById("email")
const form = document.getElementById("password")
const form = document.getElementById("form")