# Generated by Django 4.1 on 2024-11-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("his_titulo", models.CharField(max_length=96)),
                ("his_sinopse", models.CharField(max_length=255, null=True)),
                ("his_descricao", models.CharField(max_length=255, null=True)),
                ("his_enredo", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "historia",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_nome", models.CharField(max_length=60, null=True)),
                ("user_email", models.EmailField(max_length=256, unique=True)),
                ("user_senha", models.CharField(max_length=256, null=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="Personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pers_nome", models.CharField(max_length=96)),
                ("pers_personalidade", models.CharField(max_length=64, null=True)),
                ("pers_idade", models.SmallIntegerField(null=True)),
                ("pers_aparencia", models.CharField(max_length=255, null=True)),
                ("pers_sonhos", models.CharField(max_length=255, null=True)),
                ("pers_defeitos", models.CharField(max_length=255, null=True)),
                (
                    "pers_his_fk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.historia",
                    ),
                ),
            ],
            options={
                "db_table": "personagem",
            },
        ),
        migrations.AddField(
            model_name="historia",
            name="his_user_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Cenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cen_cultura", models.CharField(max_length=255, null=True)),
                ("cen_descricao", models.CharField(max_length=255, null=True)),
                ("cen_fauna", models.CharField(max_length=255, null=True)),
                (
                    "cen_his_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.historia",
                    ),
                ),
            ],
            options={
                "db_table": "cenario",
            },
        ),
    ]
