# Generated by Django 4.1 on 2024-11-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='pers_aparencia',
            new_name='pers_caracteristica',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='pers_personalidade',
            new_name='pers_genero',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='pers_defeitos',
            new_name='pers_historia',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='pers_sonhos',
            new_name='pers_objetivo',
        ),
    ]
